baseURL = "https://nikimanoledaki.com/"
languageCode = "en"
title = "Niki Manoledaki"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"
