languageCode = "en"
languageName = "English"
weight = 1
title = "Niki Manoledaki"

[params]
  displayName = "Niki Manoledaki"
  isoCode = "en"

[params.author]
  name = "Niki Manoledaki"
  image = "img/author.jpeg"
  headline = "Cloud Costs & Carbon, Platform Engineering, Kubernetes, OSS"
  links = []
