[[main]]
  name = "Talks"
  pageRef = "talks"
  weight = 20

[[main]]
  name = "Community"
  pageRef = "community"
  weight = 25

[[main]]
  name = "Media"
  pageRef = "media"
  weight = 30

[[main]]
  name = "Podcasts"
  pageRef = "podcasts"
  weight = 40

# [[main]]
#   name = "Blog"
#   pageRef = "posts"
#   weight = 50
