colorScheme = "paper"
defaultAppearance = "light"
autoSwitchAppearance = false
showAppearanceSwitcher = false
enableSearch = false
enableCodeCopy = true

[homepage]
  layout = "hero"
  showRecent = false

[article]
  showDate = true
  showReadingTime = false
  showWordCount = false
  showTableOfContents = false
  showTaxonomies = false
  showAuthor = false

[list]
  showCards = false
  groupByYear = false
  showSummary = true

[taxonomy]
  showTermCount = true

[footer]
  showAppearanceSwitcher = false
  showThemeAttribution = false
